import { createClient } from 'npm:@supabase/supabase-js@2.45.1';

const serviceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const db = createClient(Deno.env.get('SUPABASE_URL')!, serviceKey, {auth:{persistSession:false}});
const headers = ['ID','Título','Resumen','Artículo completo','Fuente URL','Fuente nombre','Categoría','Región','Imagen URL','Publicar en (ISO con zona)','ESTADO','URL publicada','Revisión','Error','Actualizado'];
const tab = 'EDITORIAL WEB';
const states = ['En revisión','Aprobado','Rechazado','Publicado'];
const uuid = /^[\da-f]{8}-[\da-f]{4}-[\da-f]{4}-[\da-f]{4}-[\da-f]{12}$/i;
const hash = async (s:string) => Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))),x=>x.toString(16).padStart(2,'0')).join('');
function check(r:{data:any;error:any}):any {if(r.error)throw new Error(r.error.message);return r.data;}
async function config(){return check(await db.from('editorial_bridge_config').select('*').eq('id',true).single());}
async function cryptKey(){return crypto.subtle.importKey('raw',await crypto.subtle.digest('SHA-256',new TextEncoder().encode(serviceKey)), 'AES-GCM',false,['encrypt','decrypt']);}
async function seal(v:unknown){const iv=crypto.getRandomValues(new Uint8Array(12));const b=await crypto.subtle.encrypt({name:'AES-GCM',iv},await cryptKey(),new TextEncoder().encode(JSON.stringify(v)));return btoa(String.fromCharCode(...iv))+'.'+btoa(String.fromCharCode(...new Uint8Array(b)));}
async function unseal(v:string){const [a,b]=v.split('.');const bytes=(s:string)=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));return JSON.parse(new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:bytes(a)},await cryptKey(),bytes(b))));}

type Payload={title:string;summary:string;body:string;sourceUrl:string;sourceName:string;category:string;region:string;imageUrl:string;scheduledAt:string};
function payload(p:any):Payload {
 const get=(k:string,max:number,required=false)=>{const v=String(p[k]??'').trim();if(v.length>max||required&&!v)throw new Error('Revisa '+k);return v;};
 const out={title:get('title',180,true),summary:get('summary',1400,true),body:get('body',40000,true),sourceUrl:get('sourceUrl',2000,true),sourceName:get('sourceName',200,true),category:get('category',120,true),region:get('region',120,true),imageUrl:get('imageUrl',2000),scheduledAt:get('scheduledAt',80)};
 for(const k of ['sourceUrl','imageUrl'] as const){if(!out[k])continue;const u=new URL(out[k]);if(!['https:','http:'].includes(u.protocol)||u.username||u.password)throw new Error('URL inválida: '+k);}
 if(out.scheduledAt&&(!/(Z|[+-]\d{2}:\d{2})$/.test(out.scheduledAt)||!Number.isFinite(Date.parse(out.scheduledAt))))throw new Error('Usa fecha ISO con zona horaria: 2026-10-03T09:15:00-05:00');
 return out;
}
function fromRow(r:any[]){return payload(Object.fromEntries(['title','summary','body','sourceUrl','sourceName','category','region','imageUrl','scheduledAt'].map((k,i)=>[k,r[i+1]??''])));}
function rowData(d:any){const p=d.payload;return [d.id,p.title,p.summary,p.body,p.sourceUrl,p.sourceName,p.category,p.region,p.imageUrl,p.scheduledAt,d.status,d.public_url||'',d.revision,d.last_error||'',d.updated_at];}
async function googleToken(c:any){const g=await unseal(c.google_cipher);const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',body:new URLSearchParams({client_id:g.clientId,client_secret:g.clientSecret,refresh_token:g.refreshToken,grant_type:'refresh_token'})});const v=await r.json();if(!r.ok||!v.access_token)throw new Error('Google necesita renovar autorización desde Social Manager');return v.access_token;}
async function google(token:string,path:string,body?:unknown,method?:string){for(let i=0;i<3;i++){const r=await fetch('https://sheets.googleapis.com/v4/spreadsheets/'+path,{method:method||(body?'POST':'GET'),headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(20000)});if(r.ok)return r.json();if(r.status===429&&i<2){await new Promise(resolve=>setTimeout(resolve,1000*(i+1)));continue;}const err=await r.json().catch(()=>({}));throw new Error('Google Sheets rechazó la operación ('+r.status+'): '+String(err.error?.message||'Revisa el archivo').slice(0,500));}throw new Error('Google ocupado');}
async function sheetRows(c:any,t:string){const r=await google(t,c.spreadsheet_id+'/values/'+encodeURIComponent("'"+tab+"'!A1:O2001"));const rows=r.values||[];if(JSON.stringify(rows[0])!==JSON.stringify(headers))throw new Error('La cabecera de EDITORIAL WEB cambió. Restaura sus 15 columnas.');return rows.slice(1);}
async function setupSheet(c:any,t:string){const m=await google(t,c.spreadsheet_id+'?fields=sheets(properties)');let s=m.sheets.find((s:any)=>s.properties.title===tab);if(!s){const r=await google(t,c.spreadsheet_id+':batchUpdate',{requests:[{addSheet:{properties:{title:tab,gridProperties:{rowCount:2001,columnCount:15,frozenRowCount:1}}}}]});s={properties:r.replies[0].addSheet.properties};await google(t,c.spreadsheet_id+'/values/'+encodeURIComponent("'"+tab+"'!A1:O1")+'?valueInputOption=RAW',{values:[headers]},'PUT');const range={sheetId:s.properties.sheetId,startRowIndex:1,endRowIndex:2001};const rules=states.map((v,i)=>({addConditionalFormatRule:{index:i,rule:{ranges:[{...range,startColumnIndex:0,endColumnIndex:15}],booleanRule:{condition:{type:'CUSTOM_FORMULA',values:[{userEnteredValue:'=$K2="'+v+'"'}]},format:{backgroundColor:i===3?{red:.78,green:.94,blue:.81}:i===2?{red:1,green:.8,blue:.8}:i===1?{red:.8,green:.9,blue:1}:{red:1,green:.94,blue:.72}}}}}}));await google(t,c.spreadsheet_id+':batchUpdate',{requests:[{repeatCell:{range:{sheetId:s.properties.sheetId,startRowIndex:0,endRowIndex:1},cell:{userEnteredFormat:{backgroundColor:{red:.12,green:.13,blue:.16},textFormat:{bold:true,foregroundColor:{red:1,green:1,blue:1}}}},fields:'userEnteredFormat'}},{setDataValidation:{range:{...range,startColumnIndex:10,endColumnIndex:11},rule:{condition:{type:'ONE_OF_LIST',values:states.map(userEnteredValue=>({userEnteredValue}))},strict:true,showCustomUi:true}}},{setBasicFilter:{range:{sheetId:s.properties.sheetId,startRowIndex:0,endRowIndex:2001,startColumnIndex:0,endColumnIndex:15}}},{updateDimensionProperties:{range:{sheetId:s.properties.sheetId,dimension:'COLUMNS',startIndex:1,endIndex:4},properties:{pixelSize:350},fields:'pixelSize'}},{repeatCell:{range:{...range,startColumnIndex:0,endColumnIndex:15},cell:{userEnteredFormat:{wrapStrategy:'CLIP'}},fields:'userEnteredFormat.wrapStrategy'}},...rules]});}
 await sheetRows(c,t);return s.properties.sheetId;
}
async function writeDraft(c:any,t:string,d:any){const rows=await sheetRows(c,t);const hits=rows.map((r:any[],i:number)=>r[0]===d.id?i+2:0).filter(Boolean);if(hits.length>1)throw new Error('ID duplicado en el spreadsheet');if(hits.length)await google(t,c.spreadsheet_id+'/values/'+encodeURIComponent("'"+tab+"'!A"+hits[0]+':O'+hits[0])+'?valueInputOption=RAW',{values:[rowData(d)]},'PUT');else{if(rows.length>=2000)throw new Error('La cola llegó a 2000 filas; archiva las publicadas');await google(t,c.spreadsheet_id+'/values/'+encodeURIComponent("'"+tab+"'!A:O")+':append?valueInputOption=RAW&insertDataOption=INSERT_ROWS',{values:[rowData(d)]});}}
async function systemCells(c:any,t:string,index:number,d:any,expectedHash:string,expectedState:string){const rows=await sheetRows(c,t);const r=rows[index-2];if(r?.[0]!==d.id||String(r[10]||'En revisión')!==expectedState)return;try{if(await hash(JSON.stringify(fromRow(r)))!==expectedHash)return;}catch{return;}await google(t,c.spreadsheet_id+'/values/'+encodeURIComponent("'"+tab+"'!K"+index+':O'+index)+'?valueInputOption=RAW',{values:[[d.status,d.public_url||'',d.revision,d.last_error||'',d.updated_at]]},'PUT');}
async function audit(id:string|null,action:string,actor:string,revision?:number){check(await db.from('editorial_drive_audit').insert({draft_id:id,action,actor,revision}));}
async function status(c:any){return {enabled:c.enabled,connected:!!c.google_cipher,sheetUrl:c.spreadsheet_id?'https://docs.google.com/spreadsheets/d/'+c.spreadsheet_id+'/edit#gid='+c.sheet_id:null,lastSync:c.last_sync,lastError:c.last_error,intervalSeconds:60,approval:'Aprobado',tab};}
async function sync(c:any,actor:string){if(!c.enabled||!c.google_cipher)return {skipped:'Editorial pendiente de conexión'};
 const locked=check(await db.from('editorial_bridge_config').update({lock_until:new Date(Date.now()+240000).toISOString()}).eq('id',true).or('lock_until.is.null,lock_until.lt.'+new Date().toISOString()).select('id'));if(!locked.length)return {busy:true};
 let processed=0,published=0;try{const t=await googleToken(c);const rows=await sheetRows(c,t);const duplicates=new Set(rows.filter((r:any[],i:number)=>r[0]&&rows.some((other:any[],j:number)=>j!==i&&other[0]===r[0])).map((r:any[])=>r[0]));const stored=check(await db.from('editorial_drive_drafts').select('*').limit(2000));const byId=new Map(stored.map((d:any)=>[d.id,d]));
 for(let i=0;i<rows.length&&processed<20;i++){const r=rows[i],id=r[0];if(!id||!uuid.test(id)||duplicates.has(id))continue;let d:any=byId.get(id);if(!d)continue;
 try{const p=fromRow(r);const h=await hash(JSON.stringify(p));const changed=h!==d.content_hash;let state=String(r[10]||'En revisión');if(!states.includes(state))state='En revisión';if(changed){d=check(await db.from('editorial_drive_drafts').update({payload:p,content_hash:h,revision:d.revision+1,status:'En revisión',last_error:null,updated_at:new Date().toISOString()}).eq('id',id).eq('revision',d.revision).select('*').single());await audit(id,'Edición desde Sheet',actor,d.revision);}
 else if(d.status!==state){d=check(await db.from('editorial_drive_drafts').update({status:state,last_error:null,updated_at:new Date().toISOString()}).eq('id',id).eq('revision',d.revision).select('*').single());await audit(id,state,actor,d.revision);}
 if(d.status==='Aprobado'&&d.published_hash!==h&&(!p.scheduledAt||Date.parse(p.scheduledAt)<=Date.now())){
  const current=await sheetRows(c,t);const same=current[i];if(same?.[0]!==id||same[10]!=='Aprobado'||await hash(JSON.stringify(fromRow(same)))!==h)continue;
  check(await db.rpc('publish_editorial_drive',{p_id:id,p_hash:h,p_actor:actor}));d=check(await db.from('editorial_drive_drafts').select('*').eq('id',id).single());published++;
 }
 if(d.published_hash===h&&d.status==='Aprobado'){d=check(await db.from('editorial_drive_drafts').update({status:'Publicado'}).eq('id',id).select('*').single());}
 if(changed||d.status!==r[10]||d.public_url!==(r[11]||null)||d.last_error!==null||String(d.revision)!==String(r[12])){await systemCells(c,t,i+2,d,h,String(r[10]||'En revisión'));processed++;}
 }catch(e){const message=(e as Error).message;if(d){check(await db.from('editorial_drive_drafts').update({last_error:message}).eq('id',id));try{const current=await sheetRows(c,t);if(current[i]?.[0]===id)await google(t,c.spreadsheet_id+'/values/'+encodeURIComponent("'"+tab+"'!N"+(i+2))+'?valueInputOption=RAW',{values:[[message]]},'PUT');}catch{}} // Keep the row and retry; never silently mark published.
 }
 }
 check(await db.from('editorial_bridge_config').update({last_sync:new Date().toISOString(),last_error:null}).eq('id',true));return {processed,published};
 }catch(e){check(await db.from('editorial_bridge_config').update({last_error:(e as Error).message}).eq('id',true));throw e;}finally{check(await db.from('editorial_bridge_config').update({lock_until:null}).eq('id',true));}
}

Deno.serve(async (req:Request)=>{try{
 if(req.method!=='POST')return Response.json({error:'Método no permitido'},{status:405});
 const c=await config();const token=req.headers.get('authorization')?.replace(/^Bearer /,'')||'';const key=req.headers.get('x-editorial-key')||'';
 const bridge=!!key&&await hash(key)===c.key_hash;let actor='Servicio editorial';let admin=false;
 if(!bridge&&token!==serviceKey){const u=await db.auth.getUser(token);if(!u.data.user)return Response.json({error:'No autorizado'},{status:401});const roles=check(await db.from('user_roles').select('roles(name)').eq('user_id',u.data.user.id));admin=roles.some((r:any)=>(Array.isArray(r.roles)?r.roles[0]:r.roles)?.name==='admin');if(!admin)return Response.json({error:'Solo administradores'},{status:403});actor=u.data.user.id;}
 const p=await req.json();if(token===serviceKey&&typeof p.actor==='string'&&uuid.test(p.actor))actor=p.actor;if(bridge){if(c.owner_id&&p.owner!==c.owner_id&&p.action!=='sync')return Response.json({error:'Propietario incorrecto'},{status:403});actor=p.owner||'Sincronización automática';}
 switch(p.action){
 case 'setup': {if(!bridge||!p.owner)throw new Error('La conexión se activa desde Social Manager');if(c.google_cipher&&c.enabled)return Response.json(await status(c));const g=p.google;if(!g?.clientId||!g?.clientSecret||!g?.refreshToken)throw new Error('Google no está conectado');if(!/^[\w-]+$/.test(p.spreadsheetId))throw new Error('Spreadsheet inválido');const next={...c,google_cipher:await seal(g),spreadsheet_id:p.spreadsheetId};const t=await googleToken(next);next.sheet_id=await setupSheet(next,t);check(await db.from('editorial_bridge_config').update({owner_id:p.owner,google_cipher:next.google_cipher,spreadsheet_id:next.spreadsheet_id,sheet_id:next.sheet_id,enabled:true,last_error:null}).eq('id',true));await audit(null,'Editorial conectado',actor);return Response.json(await status({...next,enabled:true}));}
 case 'status':return Response.json(await status(c));
 case 'list':return Response.json({status:await status(c),drafts:check(await db.from('editorial_drive_drafts').select('*').order('updated_at',{ascending:false}).limit(200)),history:check(await db.from('editorial_drive_audit').select('*').order('created_at',{ascending:false}).limit(30))});
 case 'sync':return Response.json(await sync(c,actor));
 case 'pause':check(await db.from('editorial_bridge_config').update({enabled:p.enabled===true}).eq('id',true));await audit(null,p.enabled?'Reanudado':'Pausado',actor);return Response.json(await status(await config()));
 case 'save': {if(!c.enabled)throw new Error('Conecta el editorial primero');const data=payload(p.data);const h=await hash(JSON.stringify(data));const id=p.id||crypto.randomUUID();if(!uuid.test(id))throw new Error('ID inválido');const old=check(await db.from('editorial_drive_drafts').select('*').eq('id',id).maybeSingle());if(old&&p.revision!==old.revision)throw new Error('El borrador cambió; recarga antes de guardar');const d={id,payload:data,content_hash:h,status:'En revisión',revision:(old?.revision||0)+1,last_error:null,updated_at:new Date().toISOString()};const r=old?await db.from('editorial_drive_drafts').update(d).eq('id',id).eq('revision',old.revision).select('*').single():await db.from('editorial_drive_drafts').insert(d).select('*').single();const saved=check(r);try{await writeDraft(c,await googleToken(c),saved);}catch(e){check(await db.from('editorial_drive_drafts').update({last_error:(e as Error).message}).eq('id',id));throw e;}await audit(id,'Borrador guardado',actor,saved.revision);return Response.json(saved);}
 case 'decision': {if(!['Aprobado','Rechazado','En revisión'].includes(p.state))throw new Error('Estado inválido');if(bridge&&p.state==='Aprobado'&&p.confirm!==true)throw new Error('La aprobación requiere instrucción expresa del usuario');const d=check(await db.from('editorial_drive_drafts').select('*').eq('id',p.id).single());if(d.revision!==p.revision)throw new Error('La versión cambió; recarga antes de aprobar');const t=await googleToken(c);const rows=await sheetRows(c,t);const hits=rows.map((r:any[],i:number)=>r[0]===d.id?i: -1).filter((i:number)=>i>=0);if(hits.length!==1)throw new Error('No se encontró una fila única');const row=rows[hits[0]];if(await hash(JSON.stringify(fromRow(row)))!==d.content_hash)throw new Error('Hay cambios en Drive; sincroniza y revísalos antes de aprobar');await google(t,c.spreadsheet_id+'/values/'+encodeURIComponent("'"+tab+"'!K"+(hits[0]+2))+'?valueInputOption=RAW',{values:[[p.state]]},'PUT');check(await db.from('editorial_drive_drafts').update({status:p.state,last_error:null,updated_at:new Date().toISOString()}).eq('id',d.id).eq('revision',d.revision));await audit(d.id,p.state,actor,d.revision);return Response.json({saved:true,state:p.state,automatic:true});}
 default:return Response.json({error:'Acción desconocida'},{status:400});
 }
 }catch(e){return Response.json({error:(e as Error).message},{status:400});}});
