'use client';
import {useEffect,useState} from 'react';

const blank={title:'',summary:'',body:'',sourceUrl:'',sourceName:'',category:'General',region:'Puerto Rico',imageUrl:'',scheduledAt:'',facebookSelected:false,facebookCaption:''};
const editable=(d:any)=>({...blank,...d.payload,facebookSelected:d.facebook_selected===true,facebookCaption:d.facebook_caption||''});
export default function EditorialPanel(){const [queue,setQueue]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState<any>(null),[draft,setDraft]=useState(blank),[filter,setFilter]=useState('En revisión'),[loadedCover,setLoadedCover]=useState(''),[failedCover,setFailedCover]=useState('');
 async function load(){try{const r=await fetch('/api/admin/editorial-drive',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error);setQueue(d);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{void load();const i=setInterval(load,30000);return ()=>clearInterval(i);},[]);
 async function action(p:any){setBusy(true);setError('');try{const r=await fetch('/api/admin/editorial-drive',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});const d=await r.json();if(!r.ok)throw new Error(d.error);await load();return d;}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const rows=(queue?.drafts||[]).filter((d:any)=>filter==='Todos'||d.status===filter);
 return <section className="editorial-panel"><header><p className="eyebrow">SIN PELOS · EDITORIAL</p><h1>Del borrador a la página</h1><p>Revisa aquí o en Drive. Solo lo aprobado se publica. Facebook se activa únicamente en las noticias que marques.</p><div className="editorial-toolbar">{queue?.status?.sheetUrl&&<a className="button" href={queue.status.sheetUrl} target="_blank" rel="noreferrer">Abrir EDITORIAL WEB en Drive</a>}<a className="button secondary" href="https://sin-pelos-social-manager.sinpelos.chatgpt.site/editorial" target="_blank" rel="noreferrer">Agente en ChatGPT</a><button disabled={busy} onClick={()=>{setSelected({});setDraft(blank);}}>Nuevo borrador</button></div></header>
 {error&&<p role="alert" className="editorial-error">{error}</p>}
 <div className="editorial-health"><strong>{queue?.status?.enabled?'Publicación automática activa':'Publicación automática pausada'}</strong><span>Comprueba Drive cada minuto · {queue?.status?.lastSync?'Última revisión: '+new Date(queue.status.lastSync).toLocaleString('es',{timeZone:'America/Chicago'}):'Esperando primera revisión'}</span>{queue?.status?.lastError&&<p role="alert">{queue.status.lastError}</p>}<div><button disabled={busy} onClick={()=>action({action:'sync'})}>Comprobar ahora</button><button disabled={busy} onClick={()=>action({action:'pause',enabled:!queue?.status?.enabled})}>{queue?.status?.enabled?'Pausar':'Reanudar'}</button></div></div>
 <div className="editorial-toolbar"><label>Estado <select value={filter} onChange={e=>setFilter(e.target.value)}>{['En revisión','Aprobado','Publicado','Rechazado','Todos'].map(s=><option key={s}>{s}</option>)}</select></label><span>{rows.length} artículos</span></div>
 <div className="editorial-grid"><div className="editorial-queue">{rows.length?rows.map((d:any)=><button className="editorial-item" key={d.id} onClick={()=>{setSelected(d);setDraft(editable(d));}}>{d.payload.imageUrl&&<img src={d.payload.imageUrl} alt={'Portada de '+d.payload.title} loading="lazy" style={{width:'100%',maxHeight:140,objectFit:'contain',background:'#111',borderRadius:8}}/>}<span>{d.status} · v{d.revision}</span><strong>{d.payload.title}</strong><small>{d.payload.region} · {d.payload.sourceName}</small>{d.last_error&&<small className="editorial-error">{d.last_error}</small>}</button>):<p>No hay artículos en este estado. Los borradores que prepares desde ChatGPT aparecen aquí y en Drive.</p>}</div>
 {selected&&<article className="editorial-editor"><h2>{selected.id?'Revisar artículo':'Nuevo borrador'}</h2><section aria-label="Vista previa de la portada" style={{margin:'20px 0',padding:16,border:'1px solid #444',borderRadius:12}}><h3>Portada de la noticia</h3>{draft.imageUrl?<><img key={draft.imageUrl} src={draft.imageUrl} alt={'Portada de '+(draft.title||'la noticia')} onLoad={()=>{setLoadedCover(draft.imageUrl);setFailedCover('');}} onError={()=>{setLoadedCover('');setFailedCover(draft.imageUrl);}} style={{display:'block',width:'100%',maxHeight:480,objectFit:'contain',background:'#111',borderRadius:8}}/>{failedCover===draft.imageUrl?<p role="alert">No se pudo cargar la portada. Corrige el enlace antes de aprobar.</p>:loadedCover!==draft.imageUrl?<p role="status">Cargando portada…</p>:<a href={draft.imageUrl} target="_blank" rel="noopener noreferrer">Abrir portada en tamaño completo</a>}</>:<p>Falta la portada. Añade la imagen para revisarla antes de aprobar.</p>}<p>{draft.title}</p></section><form onSubmit={async e=>{e.preventDefault();const d=await action({action:'save',id:selected.id,revision:selected.revision,data:draft});if(d){setSelected(d);setDraft(editable(d));}}}>{Object.entries({title:'Título',summary:'Resumen',body:'Artículo completo',sourceUrl:'Enlace de la fuente',sourceName:'Nombre de la fuente',category:'Categoría',region:'Región',imageUrl:'Imagen (URL, opcional)',scheduledAt:'Fecha ISO con zona (opcional)'}).map(([key,label])=><label key={key}>{label}{['summary','body'].includes(key)?<textarea required value={(draft as any)[key]} rows={key==='body'?14:3} onChange={e=>setDraft({...draft,[key]:e.target.value})}/>:<input required={!['imageUrl','scheduledAt'].includes(key)} type={['imageUrl','sourceUrl'].includes(key)?'url':'text'} value={(draft as any)[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})}/>}</label>)}<fieldset><legend>Distribución de esta noticia</legend><label><input type="checkbox" style={{width:"auto"}} checked={draft.facebookSelected} onChange={e=>setDraft({...draft,facebookSelected:e.target.checked})}/> Publicar también en Facebook al aprobar</label><p>Desmarcado: solo se publica en la web. Marcado: foto + estado + comentario con enlace al artículo completo.</p><label>Estado flow Sin Pelos<textarea value={draft.facebookCaption} maxLength={2000} rows={4} required={draft.facebookSelected} onChange={e=>setDraft({...draft,facebookCaption:e.target.value})}/></label><p>El comentario se publica automáticamente. El fijado queda pendiente para hacerlo desde Facebook.</p></fieldset><button disabled={busy}>Guardar para revisión</button></form>
 {selected.id&&<div className="editorial-toolbar"><button disabled={busy||!draft.imageUrl||loadedCover!==draft.imageUrl||JSON.stringify(draft)!==JSON.stringify(editable(selected))} onClick={()=>action({action:'decision',id:selected.id,revision:selected.revision,state:'Aprobado'})}>Aprobar esta versión</button><button disabled={busy} onClick={()=>action({action:'decision',id:selected.id,revision:selected.revision,state:'Rechazado'})}>Rechazar</button>{selected.public_url&&<a href={selected.public_url} target="_blank" rel="noreferrer">Ver publicado</a>}</div>}{selected.facebook_delivery&&<aside><strong>Facebook: {selected.facebook_delivery.state}</strong><p>{selected.facebook_delivery.detail}</p><p>Comentario: {selected.facebook_delivery.comment_state} · {selected.facebook_delivery.pin_state}</p>{selected.facebook_delivery.post_url&&<a href={selected.facebook_delivery.post_url} target='_blank' rel='noreferrer'>Abrir publicación en Facebook</a>}</aside>}<p>Guarda los cambios antes de aprobar. Si no asignas fecha, se publicará en la siguiente revisión automática.</p></article>}</div>
 <details><summary>Historial de operaciones</summary>{(queue?.history||[]).map((h:any)=><p key={h.id}>{h.action} · {new Date(h.created_at).toLocaleString('es',{timeZone:'America/Chicago'})}{h.revision?' · v'+h.revision:''}</p>)}</details></section>;
}
